# Generated by Django 4.2.7 on 2023-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_user_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
